import { StyleSheet } from "react-native";

const styles = StyleSheet.create({
  container: {
    alignItems: "center",
    flex: 1,
    backgroundColor: "white",
  },
  logo: {
    width: 200,
    height: 200,
    resizeMode: "contain",
  },
  inputemailusername: {
    width: 300,
    height: 48,
    borderColor: "red",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
  },
  inputemailusername2: {
    width: 300,
    height: 48,
    borderColor: "#eaeaea",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
  },
  username: {
    width: 300,
    height: 48,
    borderColor: "red",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
    marginTop: 20,
  },
  username2: {
    width: 300,
    height: 48,
    borderColor: "#eaeaea",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
    marginTop: 20,
  },
  passwordinput: {
    width: 300,
    height: 48,
    borderColor: "red",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
    marginTop: 20,
  },
  passwordinput2: {
    width: 300,
    height: 48,
    borderColor: "#eaeaea",
    borderWidth: 2,
    borderRadius: 7,
    backgroundColor: "#fafafa",
    paddingLeft: 10,
    marginTop: 20,
  },
  btn: {
    width: 300,
    height: 48,
    backgroundColor: "#0095f6",
    marginTop: 20,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
    opacity: 0.4,
  },
  btn2: {
    width: 300,
    height: 48,
    backgroundColor: "#0095f6",
    marginTop: 20,
    borderRadius: 7,
    justifyContent: "center",
    alignItems: "center",
  },
  btntext: {
    color: "white",
    fontWeight: "bold",
    fontSize: 14,
  },
  bottomstuff: {
    position: "absolute",
    bottom: 0,
    backgroundColor: "#fafafa",
    width: "100%",
    height: 50,
    alignItems: "center",
    justifyContent: "center",
    flexDirection: "row",
  },
});

export default styles;
